### ISSUE TITLE
HackMD instructions assume you have a checkout of the repository

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#44]
**Describe the bug**

**To Reproduce**
1. Go to 'https://github.com/FAIRplus/the-fair-cookbook/blob/dev/docs/content/recipes/help/how-to-create-recipe-with-hackmd.md'
2. Step 5 assumes that you have the Cookbook checked out somewhere but there are no instructions/links earlier in the recipe that tell you that you need to have done this.

**Comment by proccaserra** [comment]
@AlasdairGray it seems you skipped Step 4. closing this (non) issue.

**Comment by AlasdairGray** [comment]
Except that step 4 assumes that you have already cloned the repo which is not stated anywhere in the recipe.

I thought that part of the point of using HackMD was to avoid you needing to clone and checkout the repo locally.

**Comment by proccaserra** [comment]
That was simply an incorrect assumption from your side @AlasdairGray. 
I have however extended the help following discussion with @petrospaps and @FuqiX 
Many users are very happy with the tool and it does improve productivity. 

Closing now. thx

**Comment by AlasdairGray** [comment]
Given that the recipe is starting at the point of creating a github account I really think that step 4 should be clone the repo, then carry on the rest of the recipe.

**Comment by FuqiX** [comment]
I don't think one need to clone the repo to push to the repo. 

I guess Alasdair faces this problem because HackMD only allows repo  __Admins__ to push a recipe to the repo. If one has 'write' permission only, then they can't connect to the doc with the Cookbook Repo.

Possible solutions:
1. make all authors admins.
2. transfer the hackmd doc ownership to an admin account. The admin is in charge of linking the recipe to the github repo. It won't affect other things.
Any suggestions?

**Comment by daniwelter** [comment]
Fixed in commit c189e4048d2357abc693ae7ce2a8704ff211b2b9
