### ISSUE TITLE
How to integrate a new Recipe in the Book: Improve TOC building process and Documentation: 

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#47]
**Is your feature request related to a problem? Please describe.**
As the author of a recipe, I don't know the official procedure for having it placed in the Book Table of Content.
Do I need to push both the `Recipe and `toc.yml` or just the recipe?

**Comment by FuqiX** [comment]
Previous discussion on where to put R4 'How to build an application ontology with ROBOT'

__Emiliano__ : R4 should be in Chapter 5 "Recipes and Guided Examples" subsection 5.3.3 - Making data and services FAIR by design - or subsection 5.4 - FAIRification for reuse by industry - might be good places for the recipe.

__Fuqi__:  I prefer putting all UC3 recipes in a bundle (we have around 7 ontology-related recipes), and add them together as a subsection in the cookbook. I think 3.3.1.4. Vocabulary servers and Terminology management  or an extra data annotation section after 3.3.2. Conversion / Transformation services and ETL procedures might also be good to host the recipes. Putting them in subsection 5.3.3 also makes sense. But the focus will be different.

__Danielle__: There are a number of sections in the cookbook ToC where I think R4 might fit but not one that jumps out at me as the perfect fit. Section 5 is definitely a good option but I would also consider either "3.3.1.3. Semantic Interoperability Standards: Shared understanding" or as Fuqi suggests, an additional data annotation section after 3.3.2.

I somewhat disagree that all ontology recipes should live together since they address different aspects of UC3 and by extension, different aspects of FAIR.
