### ISSUE TITLE
highlight executable recipes (jupyter notebooks) from the TOC / left menu

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#471]
suggestion / request from @AlasdairGray during 2022.07.27 book dash.

-[ ] check if possible to include an icon
-[ ] check if possible to color code .md vs .ipynb

**Comment by terazus** [comment]
This is very hard as far as I know. It requires to modify the python function that generates the tree of content HTML from the toc file, which itself requires us to create a custom theme.

**Comment by AlasdairGray** [comment]
For now I'd suggest going for the simple option of having something on the card summary.

**Comment by AlasdairGray** [comment]
An option could be that we put a ` *` on the end of the title of recipes that have a notebook. That would then appear in the TOC without any scripting.

**Comment by terazus** [comment]
I actually found a solution to inject content in the navbar.
Here is an example where executable recipes are suffixed by a 'play' icon
![image](https://user-images.githubusercontent.com/6538906/181915687-1cb168f7-b833-426e-b282-599cc0937921.png)

**Comment by terazus** [comment]
I've been able to find a way to inject content in the HTML of the navigation content. Using the cards for each recipe, I can create a data structure consumable by the JavaScript module that can then map the names of each link and the title of each card.
This is something i've used to create an alternative search page for the recipes (see https://faircookbookdev.netlify.app/content/search-wizard.html, warning: it's work in progress)

Unfortunatly, some cards don't have the same title as the page they are one. Thus, the recipe can't be mapped and are ignored.
Below is an example where the recipe "Clinical Genetic Information as FHIR JSON" (the last one) should have executable code but doesn't show the icon because the corresponding card title is "File conversion, VCF to FHIR".

![image](https://user-images.githubusercontent.com/6538906/181916257-ac3d53b2-b749-4b16-8a09-790c2924a097.png)

**Comment by terazus** [comment]
Depend on issue #489
